spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #authentication-database: [authentication_database]
      #username: [username]
      #password: [password]
      database: itcrowd_dev