spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #authentication-database: [authentication_database]
      #username: [username]
      #password: [password]
      database: itcrowd_dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

files:
  upload-dir: uploads

